autoCode:
  outDir: d://autoCode
  author: mhs
  dbType: mysql
  driverName: com.mysql.jdbc.Driver
  userName: root
  password: mhs471002385%
  url: jdbc:mysql://132.232.87.134:3306/wx?characterEncoding=utf8&useSSL=false